{% set name = "dokter" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dokter-{{ version }}.tar.gz
  sha256: 02b646e0bdabb771b7a64f935f12557b4aa4fdf8112c8d34c91599a26039fb60

build:
  entry_points:
    - dokter=dokter.main:dokter
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - shellcheck

test:
  requires:
    - python {{ python_min }}
  imports:
    - dokter
  commands:
    - dokter --help

about:
  home: https://gitlab.com/gitlab-org/incubation-engineering/ai-assist/dokter
  summary: Make your Dockerfiles better
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
