{% set name = "dokter" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dokter-{{ version }}.tar.gz
  sha256: 8ade149c3395faa545bc6b906b979e9b67f16966e34418af9ec69c6ddfe46c6a

build:
  entry_points:
    - dokter=dokter.main:dokter
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - shellcheck

test:
  imports:
    - dokter
  commands:
    - dokter --help

about:
  home: https://gitlab.com/gitlab-org/incubation-engineering/ai-assist/dokter
  summary: Make your Dockerfiles better
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
